---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 3000, host: 3000}]
provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      customize:
        memory: 4096

suites:
  - name: default
    run_list:
      - recipe[rails-box::default]
    attributes: 
