name 'logger-server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures logger-server'
long_description 'Installs/Configures logger-server'
version '0.1.0'

depends 'apt'
depends 'nginx'
depends 'htpasswd'
depends 'java'
depends 'elasticsearch'
depends 'logstash'
depends 'kibana_lwrp', '~>3.0.2', git: 'https://github.com/lusis/chef-kibana.git'
