---
driver:
  name: vagrant

provisioner:
  name: chef_zero_scheduled_task

platforms:
  - name: opentable/win-2012r2-standard-amd64-nocm

suites:
  - name: default
    run_list:
      - recipe[sql-server::default]
    attributes:
