name 'jenkins-box'
maintainer 'Ezra Rush'
maintainer_email 'rushwest@gmail.com'
license 'MIT'
description 'Installs/Configures jenkins-box'
long_description 'Installs/Configures jenkins-box'
version '0.1.0'

depends 'apt'
depends 'iptables'
depends 'jenkins'
depends 'nginx'
depends 'rvm'
depends 'nodejs'
