name 'jenkins-svn-box'
maintainer 'Ezra Rush'
maintainer_email 'rushwest@gmail.com'
license 'MIT'
description 'Installs/Configures a Jenkins CI Sever'
long_description 'Installs/Configures a Jenkins CI server with a job to run tests a a rails project'
version '0.1.0'

depends 'apt'
depends 'iptables'
depends 'jenkins'
depends 'apache2'
depends 'rbenv'
depends 'nodejs'
